name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl:
          - "5.32"
          - "5.38"
          - "5.42"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Show Perl
        run: |
          perl -v
          perl -V:archname

      - name: Install dependencies
        run: |
          cpanm --version
          cpanm --notest --installdeps .

      - name: Run tests
        run: |
          prove -l
